version: "1.0"
services:
  esrgan:
    build: .
    volumes:
      - /shared/ai/media/esrgan/output:/results
      - /shared/ai/media:/inputs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
